/**
 * Tech database — popular technologies with their
 * Simple Icons slug and brand color.
 *
 * Users can always type a custom name/slug; this list
 * just powers suggestions and quick-picks.
 */
const TECH_DB = [
  { name: "React", slug: "react", color: "61DAFB" },
  { name: "TypeScript", slug: "typescript", color: "3178C6" },
  { name: "JavaScript", slug: "javascript", color: "F7DF1E" },
  { name: "Next.js", slug: "nextdotjs", color: "000000" },
  { name: "Node.js", slug: "nodedotjs", color: "5FA04E" },
  { name: "Python", slug: "python", color: "3776AB" },
  { name: "Docker", slug: "docker", color: "2496ED" },
  { name: "PostgreSQL", slug: "postgresql", color: "4169E1" },
  { name: "GitHub", slug: "github", color: "181717" },
  { name: "Tailwind CSS", slug: "tailwindcss", color: "06B6D4" },
  { name: "Vue.js", slug: "vuedotjs", color: "4FC08D" },
  { name: "Angular", slug: "angular", color: "0F0F11" },
  { name: "Svelte", slug: "svelte", color: "FF3E00" },
  { name: "Go", slug: "go", color: "00ADD8" },
  { name: "Rust", slug: "rust", color: "000000" },
  { name: "Java", slug: "openjdk", color: "437291" },
  { name: "C#", slug: "csharp", color: "512BD4" },
  { name: "Swift", slug: "swift", color: "F05138" },
  { name: "Kotlin", slug: "kotlin", color: "7F52FF" },
  { name: "Ruby", slug: "ruby", color: "CC342D" },
  { name: "PHP", slug: "php", color: "777BB4" },
  { name: "MongoDB", slug: "mongodb", color: "47A248" },
  { name: "Redis", slug: "redis", color: "FF4438" },
  { name: "MySQL", slug: "mysql", color: "4479A1" },
  { name: "AWS", slug: "amazonwebservices", color: "232F3E" },
  { name: "Google Cloud", slug: "googlecloud", color: "4285F4" },
  { name: "Azure", slug: "microsoftazure", color: "0078D4" },
  { name: "Firebase", slug: "firebase", color: "DD2C00" },
  { name: "Vercel", slug: "vercel", color: "000000" },
  { name: "Render", slug: "render", color: "46E3B7" },
  { name: "Netlify", slug: "netlify", color: "00C7B7" },
  { name: "Git", slug: "git", color: "F05032" },
  { name: "Linux", slug: "linux", color: "FCC624" },
  { name: "Ubuntu", slug: "ubuntu", color: "E95420" },
  { name: "Nginx", slug: "nginx", color: "009639" },
  { name: "GraphQL", slug: "graphql", color: "E10098" },
  { name: "Sass", slug: "sass", color: "CC6699" },
  { name: "Webpack", slug: "webpack", color: "8DD6F9" },
  { name: "Vite", slug: "vite", color: "646CFF" },
  { name: "ESLint", slug: "eslint", color: "4B32C3" },
  { name: "Prettier", slug: "prettier", color: "F7B93E" },
  { name: "Jest", slug: "jest", color: "C21325" },
  { name: "Cypress", slug: "cypress", color: "69D3A7" },
  { name: "Figma", slug: "figma", color: "F24E1E" },
  { name: "Notion", slug: "notion", color: "000000" },
  { name: "Slack", slug: "slack", color: "4A154B" },
  { name: "Discord", slug: "discord", color: "5865F2" },
  { name: "Electron", slug: "electron", color: "47848F" },
  { name: "Flutter", slug: "flutter", color: "02569B" },
  { name: "Dart", slug: "dart", color: "0175C2" },
  { name: "React Native", slug: "react", color: "61DAFB" },
  { name: "Expo", slug: "expo", color: "000020" },
  { name: "HTML5", slug: "html5", color: "E34F26" },
  { name: "CSS3", slug: "css3", color: "1572B6" },
  { name: "Nuxt.js", slug: "nuxtdotjs", color: "00DC82" },
  { name: "Remix", slug: "remix", color: "000000" },
  { name: "Astro", slug: "astro", color: "BC52EE" },
  { name: "Deno", slug: "deno", color: "70FFAF" },
  { name: "Bun", slug: "bun", color: "000000" },
  { name: "Prisma", slug: "prisma", color: "2D3748" },
  { name: "Supabase", slug: "supabase", color: "3FCF8E" },
  { name: "Stripe", slug: "stripe", color: "635BFF" },
  { name: "Shopify", slug: "shopify", color: "7AB55C" },
  { name: "WordPress", slug: "wordpress", color: "21759B" },
  { name: "Markdown", slug: "markdown", color: "000000" },
  { name: "LaTeX", slug: "latex", color: "008080" },
  { name: "TensorFlow", slug: "tensorflow", color: "FF6F00" },
  { name: "PyTorch", slug: "pytorch", color: "EE4C2C" },
  { name: "Pandas", slug: "pandas", color: "150458" },
  { name: "NumPy", slug: "numpy", color: "013243" },
  { name: "Jupyter", slug: "jupyter", color: "F37626" },
  { name: "R", slug: "r", color: "276DC3" },
  { name: "Kubernetes", slug: "kubernetes", color: "326CE5" },
  { name: "Terraform", slug: "terraform", color: "844FBA" },
  { name: "Ansible", slug: "ansible", color: "EE0000" },
  { name: "Jenkins", slug: "jenkins", color: "D24939" },
  { name: "GitHub Actions", slug: "githubactions", color: "2088FF" },
  { name: "GitLab", slug: "gitlab", color: "FC6D26" },
  { name: "Bitbucket", slug: "bitbucket", color: "0052CC" },
  { name: "Jira", slug: "jira", color: "0052CC" },
  { name: "Confluence", slug: "confluence", color: "172B4D" },
  { name: "VS Code", slug: "visualstudiocode", color: "007ACC" },
  { name: "IntelliJ IDEA", slug: "intellijidea", color: "000000" },
  { name: "Vim", slug: "vim", color: "019733" },
  { name: "Neovim", slug: "neovim", color: "57A143" },
  { name: "Arch Linux", slug: "archlinux", color: "1793D1" },
  { name: "Debian", slug: "debian", color: "A81D33" },
  { name: "macOS", slug: "macos", color: "000000" },
  { name: "Windows", slug: "windows", color: "0078D4" },
  { name: "Android", slug: "android", color: "34A853" },
  { name: "iOS", slug: "ios", color: "000000" },
  { name: "Apple", slug: "apple", color: "000000" },
  { name: "Gemini", slug: "googlegemini", color: "8E75B2" },
  { name: "OpenAI", slug: "openai", color: "412991" },
  { name: "Claude", slug: "anthropic", color: "191919" },
  { name: "Groq", slug: "groq", color: "F55036" },
  { name: "Spotify", slug: "spotify", color: "1DB954" },
  { name: "Twitch", slug: "twitch", color: "9146FF" },
  { name: "YouTube", slug: "youtube", color: "FF0000" },
  { name: "X", slug: "x", color: "000000" },
  { name: "Instagram", slug: "instagram", color: "E4405F" },
  { name: "LinkedIn", slug: "linkedin", color: "0A66C2" },
  { name: "Jetpack Compose", slug: "jetpackcompose", color: "4285F4" },
  { name: "Material Design", slug: "materialdesign", color: "757575" },
  { name: "SQLite", slug: "sqlite", color: "003B57" },
  { name: "Room", slug: "sqlite", color: "003B57" },
  { name: "Hilt", slug: "android", color: "34A853" },
  { name: "WorkManager", slug: "android", color: "34A853" },
  { name: "Retrofit", slug: "android", color: "34A853" },
  { name: "OkHttp", slug: "android", color: "34A853" },
  { name: "Coil", slug: "android", color: "34A853" },
  { name: "DataStore", slug: "android", color: "34A853" },
  { name: "MediaPipe", slug: "google", color: "4285F4" },
  { name: "TensorFlow Lite", slug: "tensorflow", color: "FF6F00" },
  { name: "Django", slug: "django", color: "092E20" },
  { name: "Django REST Framework", slug: "django", color: "092E20" },
  { name: "JSON Web Tokens", slug: "jsonwebtokens", color: "000000" },
  { name: "OpenAPI", slug: "openapiinitiative", color: "85EA2D" },
  { name: "Gunicorn", slug: "gunicorn", color: "499848" },
  { name: "Whitenoise", slug: "python", color: "3776AB" },
  { name: "Ruff", slug: "ruff", color: "D7FF64" },
  { name: "pytest", slug: "pytest", color: "0A9EDC" },
  { name: "detekt", slug: "kotlin", color: "7F52FF" },
  { name: "gitleaks", slug: "github", color: "181717" },
  { name: "Sentry", slug: "sentry", color: "362D59" },
  { name: "Crashlytics", slug: "firebase", color: "DD2C00" },
  { name: "Remote Config", slug: "firebase", color: "DD2C00" },
  { name: "hypothesis", slug: "python", color: "3776AB" },
  { name: "pre-commit", slug: "precommit", color: "FABB00" },
  { name: "Groq", slug: "groq", color: "F55036" },
  { name: "YouTube Music API", slug: "youtubemusic", color: "FF0000" },
  { name: "REST API", slug: "restapi", color: "005571" },
  { name: "Neon", slug: "neon", color: "00E599" },
  { name: "Playwright", slug: "playwright", color: "2EAD33" },
];

const POPULAR_TECHS = [
  "React", "TypeScript", "Python", "Docker", "Next.js",
  "PostgreSQL", "GitHub", "Tailwind CSS", "Node.js", "Go"
];
